version: '3'

services:
  janus-gateway:
    image: docker-janus:latest 
    container_name: janus-gateway
    ports:
      # http
      - 8088:8088
      # https
      - 8089:8089
      # ws
      - 8188:8188
      # wss
      - 8989:8989
    restart: unless-stopped